build:
  main: main.go
  binary: meli
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386

dockers:
  -
    image: komuw/meli
    latest: true

brew:
  github:
    owner: komuw
    name: meli
  commit_author:
    name: komuW
    email: komuw05@gmail.com
  folder: HomebrewFormula
  caveats: "meli -up"
  homepage: "https://github.com/komuW/meli"
  description: "Meli is supposed to be a faster alternative to docker-compose.\n Faster in the sense that, Meli will try to pull as many services(docker containers) as it can in parallel."
  test: |
    system "#{bin}/program --version"
    ...
  install: |
    bin.install "program"

fpm:
  vendor: komuW.
  homepage: https://github.com/komuW/meli
  maintainer: komuW <komuw05@gmail.com>
  description: Meli is supposed to be a faster alternative to docker-compose.\n Faster in the sense that, Meli will try to pull as many services(docker containers) as it can in parallel.
  license: MIT
  formats:
    - deb
    - rpm

snapcraft:
  name: meli
  # 79 char long at most.
  summary: Meli is supposed to be a faster alternative to docker-compose.
  # Keep dscription under 100 words though
  description: |
    Meli is supposed to be a faster alternative to docker-compose.
    Faster in the sense that, Meli will try to pull as many services(docker containers) as it can in parallel.
  # https://snapcraft.io/docs/reference/channels
  grade: stable
  # https://snapcraft.io/docs/reference/confinement
  confinement: strict
